-- =========================================================
-- CADENCE AI ENGINE DATABASE SEED
-- File: 02_seed_kekananan.sql
-- Purpose: Insert Johor VIP kekananan / precedence leaderboard
-- =========================================================

BEGIN;

-- Clears old VIP data during testing.
-- Safe now because we are still setting up.
TRUNCATE TABLE vip_rankings, vip_profiles RESTART IDENTITY CASCADE;

CREATE TEMP TABLE seed_kekananan (
    rank_number INT,
    honorific_title VARCHAR(150),
    full_name VARCHAR(250),
    position_title VARCHAR(300)
);

INSERT INTO seed_kekananan
(rank_number, honorific_title, full_name, position_title)
VALUES
(1, 'YANG AMAT BERHORMAT', 'DATO’ ONN HAFIZ BIN GHAZI', 'MENTERI BESAR JOHOR'),
(2, 'YANG BERHORMAT', 'DATO’ MOHAMMED RIDHA BIN DATO’ ABD. KADIR', 'SETIAUSAHA KERAJAAN JOHOR, PEJABAT SETIAUSAHA KERAJAAN JOHOR'),
(3, 'YANG BERHORMAT', 'DATO’ DR. HAJI MOHD PUAD BIN ZARKASHI', 'SPEAKER DEWAN NEGERI'),
(4, 'YANG BERHORMAT', 'DATO’ ZAHARI BIN SARIP', 'PENGERUSI JAWATANKUASA PERTANIAN, INDUSTRI ASAS TANI DAN KEMAJUAN LUAR BANDAR NEGERI JOHOR'),
(5, 'YANG BERHORMAT', 'DATO’ HAJI MOHD JAFNI BIN MD SHUKOR', 'PENGERUSI JAWATANKUASA PERUMAHAN DAN KERAJAAN TEMPATAN NEGERI JOHOR'),
(6, 'YANG BERHORMAT', 'TUAN RAVEN KUMAR A/L KRISHNASAMY', 'PENGERUSI JAWATANKUASA PERPADUAN, WARISAN DAN BUDAYA NEGERI JOHOR'),
(7, 'YANG BERHORMAT', 'PUAN HAJAH KHAIRIN-NISA BINTI ISMAIL @ MD ON', 'PENGERUSI JAWATANKUASA PEMBANGUNAN WANITA, KELUARGA DAN MASYARAKAT NEGERI JOHOR'),
(8, 'YANG BERHORMAT', 'TUAN MOHD HAIRI BIN MAD SHAH', 'PENGERUSI JAWATANKUASA BELIA DAN SUKAN, PEMBANGUNAN USAHAWAN DAN KOPERASI NEGERI JOHOR'),
(9, 'YANG BERHORMAT', 'TUAN HAJI MOHD FARED BIN MOHD KHALID', 'PENGERUSI JAWATANKUASA HAL EHWAL AGAMA ISLAM NEGERI JOHOR'),
(10, 'YANG BERHORMAT', 'TUAN LING TIAN SOON', 'PENGERUSI JAWATANKUASA KESIHATAN DAN ALAM SEKITAR NEGERI JOHOR'),
(11, 'YANG BERHORMAT', 'TUAN LEE TING HAN', 'PENGERUSI JAWATANKUASA PELABURAN, PERDAGANGAN, HAL EHWAL PENGGUNA DAN SUMBER MANUSIA NEGERI JOHOR'),
(12, 'YANG BERHORMAT', 'TUAN IR. TS. MOHAMAD FAZLI BIN MOHAMAD SALLEH', 'PENGERUSI JAWATANKUASA KERJA RAYA, PENGANGKUTAN DAN INFRASTRUKTUR DAN KOMUNIKASI NEGERI JOHOR'),
(13, 'YANG BERHORMAT', 'TUAN AZNAN BIN TAMIN', 'PENGERUSI JAWATANKUASA PENDIDIKAN DAN PENERANGAN NEGERI JOHOR'),
(14, 'YANG BERHORMAT', 'DATO’ HAJI MOHD. NOORAZAM BIN DATO’ HAJI OSMAN', 'PEGAWAI KEWANGAN NEGERI JOHOR'),
(15, 'SAHIBUS SAMAHAH YANG BERHORMAT', 'DATO’ HAJI YAHYA BIN AHMAD', 'MUFTI NEGERI JOHOR'),
(16, 'YANG BERHORMAT YANG AMAT ARIF', 'DATO’ HAJI MUHAMMAD KHALDUN BIN MOHAMAD SHARIF', 'KETUA HAKIM SYARIE NEGERI JOHOR'),
(17, 'TUAN HAJI', 'AHMAD NAZIR BIN HAJI MOHD NASIR', 'TIMBALAN SETIAUSAHA KERAJAAN JOHOR (PEMBANGUNAN)'),
(18, 'YANG BERHORMAT', 'DATO’ HAJI ISMAIL BIN HAJI ABU', 'TIMBALAN SETIAUSAHA KERAJAAN JOHOR (PENGURUSAN)'),
(19, 'PUAN', 'NORLIYATI BINTI MD. NOR', 'TIMBALAN SETIAUSAHA KERAJAAN JOHOR (PEMANTAUAN PROJEK DAN KESEJAHTERAAN RAKYAT)'),
(20, 'YANG BERHORMAT', 'DATO’ HAJI ON BIN JABBAR @ JAAFAR', 'TIMBALAN SETIAUSAHA KERAJAAN JOHOR (SUKAN, BELIA DAN SUKARELAWAN)'),
(21, 'TUAN HAJI', 'NASRI BIN MD. ALI', 'PENGARAH JABATAN AGAMA ISLAM NEGERI JOHOR'),
(22, 'TUAN HAJI', 'MOHAMMED SHAKIB BIN HAJI ALI', 'PENGARAH TANAH DAN GALIAN JOHOR'),
(23, 'YANG BERHORMAT', 'DATO’ HAJI MOHD. HAFFIZ BIN HAJI AHMAD', 'DATUK BANDAR MAJLIS BANDARAYA JOHOR BAHRU'),
(24, 'TUAN HAJI', 'AHMAD NAZIR BIN HAJI MOHD NASIR', 'DATUK BANDAR MAJLIS BANDARAYA ISKANDAR PUTERI'),
(25, 'YANG BERHORMAT DATIN PADUKA', 'HAJAH HAZLINA BINTI JALIL', 'DATUK BANDAR MAJLIS BANDARAYA PASIR GUDANG'),
(26, 'YANG BERHORMAT CP DATUK', 'AB RAHAMAN BIN ARSAD', 'KETUA POLIS JOHOR'),
(27, 'YBHG. BRIG. JEN.', 'ZULHELMI BIN MASDAR', 'PANGLIMA 7 BRIGED'),
(28, 'PROF. DR.', 'MOHD SHAFRY MOHD RAHIM', 'NAIB CANSELOR UNIVERSITI TEKNOLOGI MALAYSIA (UTM) SKUDAI'),
(29, 'PROF. DR.', 'MAS FAWZI BIN MOHD ALI', 'NAIB CANSELOR UNIVERSITI TUN HUSSEIN ONN MALAYSIA'),
(30, NULL, 'NAMA BELUM DIISI - KETUA EKSEKUTIF IRDA', 'KETUA EKSEKUTIF PIHAK BERKUASA WILAYAH PEMBANGUNAN ISKANDAR (IRDA)'),
(31, 'TUAN IR.', 'ZAINAL BIN TUMIAN', 'PENGARAH KERJA RAYA JABATAN KERJA RAYA NEGERI JOHOR'),
(32, 'TUAN DR. HAJI', 'MOHTAR BIN PUNGUT @ HAJI AHMAD', 'PENGARAH KESIHATAN NEGERI JOHOR, JABATAN KESIHATAN NEGERI JOHOR'),
(33, NULL, 'NAMA BELUM DIISI - PENGARAH PENDIDIKAN NEGERI JOHOR', 'PENGARAH PENDIDIKAN NEGERI JOHOR, JABATAN PENDIDIKAN NEGERI JOHOR'),
(34, 'TUAN DR. HAJI', 'MOHD. KHALID BIN ABDUL SAMAD', 'PENGARAH PEMBANGUNAN NEGERI JOHOR'),
(35, 'ENCIK', 'HAIRUZAM BIN MOHD AMIN @ HAMIM', 'PENGARAH SURUHANJAYA PENCEGAHAN RASUAH MALAYSIA (SPRM) JOHOR'),
(36, 'TUAN IR.', 'MUHAMMAD ZAKI BIN MASHUD', 'PENGARAH PENGAIRAN DAN SALIRAN JOHOR'),
(37, 'TUAN HAJI', 'YOSRI BIN MOHD', 'PENGARAH JABATAN PERTANIAN NEGERI JOHOR');

INSERT INTO vip_profiles (
    full_name,
    honorific_title,
    position_title,
    vip_category,
    notes
)
SELECT
    full_name,
    honorific_title,
    position_title,
    'official',
    'Seeded from Susunan Kekananan Negeri Johor document'
FROM seed_kekananan
ORDER BY rank_number;

INSERT INTO vip_rankings (
    vip_id,
    rank_number,
    ranking_scope,
    source_name,
    effective_from,
    is_current,
    notes
)
SELECT
    vp.vip_id,
    sk.rank_number,
    'Johor State',
    'SUSUNAN KEKANANAN NEGERI JOHOR',
    CURRENT_DATE,
    TRUE,
    'Initial ranking seed for Cadence AI Engine'
FROM seed_kekananan sk
JOIN vip_profiles vp
    ON vp.full_name = sk.full_name
   AND vp.position_title = sk.position_title;

COMMIT;